# Automatically generated by configure - do not modify
TARGET_M68K=y
TARGET_NAME=m68k
TARGET_BASE_ARCH=m68k
TARGET_ABI_DIR=m68k
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /mnt/qemu-2.0.2/gdb-xml/cf-core.xml /mnt/qemu-2.0.2/gdb-xml/cf-fp.xml
CONFIG_I386_DIS=y
CONFIG_M68K_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
