# Automatically generated by configure - do not modify
TARGET_PPCEMB=y
TARGET_NAME=ppcemb
TARGET_BASE_ARCH=ppc
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /mnt/qemu-2.0.2/gdb-xml/power-core.xml /mnt/qemu-2.0.2/gdb-xml/power-fpu.xml /mnt/qemu-2.0.2/gdb-xml/power-altivec.xml /mnt/qemu-2.0.2/gdb-xml/power-spe.xml
CONFIG_I386_DIS=y
CONFIG_PPC_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
